GET http://localhost:4000/api/transactions

###
POST http://localhost:4000/api/transactions
Content-Type: application/json

{
  "amount": 1000,
  "date": "2-10-2024",
  "description": "Payment for services"
}

###
DELETE http://localhost:4000/api/transactions/10

###
PUT http://localhost:4000/api/transactions/1
Content-Type: application/json

{
  "amount": 1000,
  "date": "2-10-2024",
  "description": "Payment for service"
}